spring.application.name=combat

# Définition du port (pour ne pas entrer en conflit avec les autres services)
server.port=8085

# Connexion à la base de données MongoDB (collection dédiée aux combats)
# Remplace "localhost" par "mongo" si ce service tourne dans Docker
spring.data.mongodb.uri=mongodb://localhost:27017/gatcha_battles