services:
  mongodb:
    image: mongo:latest
    container_name: gatcha-mongodb-invocations
    ports:
      - "27019:27019"
    volumes:
      - mongo_data:/data/db-invocations
    restart: always

volumes:
  mongo_data: