spring.application.name=player-service
spring.data.mongodb.uri=mongodb://mongodb-invocation:27017/player-service
server.port=8082
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

