spring.application.name=player-service
spring.data.mongodb.uri=mongodb://mongo-player:27017/player_db
server.port=8082
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/v3/api-docs

